<?php 
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$num_cel=$_GET['celular'];
$ch = curl_init();
$s='{\"numero_destino\":\"'.$num_cel;
$s+='\",\"nome_produto\":\"TT-Passageiro\",\"tamanho\":\"7\",\"tts\":false}';
curl_setopt($ch, CURLOPT_URL, "https://api2.totalvoice.com.br/verificacao");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,$s);
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Content-Type: application/json";
$headers[] = "Accept: application/json";
$headers[] = "Access-Token: 701f5d02da7822df7d452dc2e40c3608";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);


//curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Access-Token: 701f5d02da7822df7d452dc2e40c3608' -d '{"numero_destino":"84996707763","nome_produto":"TT-Passageiro","tamanho":"7","tts":false}' 'https://api2.totalvoice.com.br/verificacao'

?>